insert into customer (id, username, age)values (1,'user1',30);
insert into customer (id, username, age)values (2,'user2',31);
insert into customer (id, username, age)values (3,'user3',32);
insert into customer (id, username, age)values (4,'user4',33);
insert into customer (id, username, age)values (5,'user5',34);
insert into customer (id, username, age)values (6,'user6',35);
insert into customer (id, username, age)values (7,'user7',36);
insert into customer (id, username, age)values (8,'user8',37);
insert into customer (id, username, age)values (9,'user9',38);
insert into customer (id, username, age)values (10,'user10',39);

insert into address (id, location, customer_id) values (1,'location1',1);
insert into address (id, location, customer_id) values (2,'location2',2);
insert into address (id, location, customer_id) values (3,'location3',3);
insert into address (id, location, customer_id) values (4,'location4',4);
insert into address (id, location, customer_id) values (5,'location5',5);
insert into address (id, location, customer_id) values (6,'location6',6);
insert into address (id, location, customer_id) values (7,'location7',7);
insert into address (id, location, customer_id) values (8,'location8',8);
insert into address (id, location, customer_id) values (9,'location9',9);
insert into address (id, location, customer_id) values (10,'location10',10);
